'use client'

import { useEffect } from 'react'

const SUPPORTED = ['zh-CN', 'zh-TW', 'ja', 'en'] as const
const DEFAULT = 'zh-CN'

function detectLocale(): string {
  if (typeof window === 'undefined') return DEFAULT
  try {
    const raw = localStorage.getItem('cep-settings')
    if (raw) {
      const s = JSON.parse(raw)
      if (
        s.language &&
        s.language !== 'auto' &&
        (SUPPORTED as readonly string[]).includes(s.language)
      ) {
        return s.language
      }
    }
  } catch { /* ignore */ }
  const nav = navigator.language
  const match = SUPPORTED.find((l) => l.split('-')[0] === nav.split('-')[0])
  return match ?? DEFAULT
}

/**
 * Root 404 handler. Generated by Next.js as out/404.html in production.
 *
 * Never renders UI — always redirects:
 *   - Locale-prefixed path → /<locale>/404 (React i18n 404 page)
 *   - Non-locale path → detect language → /<lang>/<path>
 */
export default function NotFound() {
  useEffect(() => {
    const seg = location.pathname.split('/')[1]

    if ((SUPPORTED as readonly string[]).includes(seg)) {
      location.replace('/' + seg + '/404' + location.search + location.hash)
      return
    }

    const locale = detectLocale()
    location.replace('/' + locale + location.pathname + location.search + location.hash)
  }, [])

  return null
}
