'use client'

import { useEffect } from 'react'
import { getExplicitLanguage, detectBrowserLocale } from '@/lib/locale-utils'

const SUPPORTED = ['zh-CN', 'zh-TW', 'ja', 'en'] as const

/**
 * Root 404 handler. Generated by Next.js as out/404.html in production.
 *
 * Never renders UI — always redirects:
 *   - Locale-prefixed path → /<locale>/404 (React i18n 404 page)
 *   - Non-locale path → detect language → /<lang>/<path>
 */
export default function NotFound() {
  useEffect(() => {
    const seg = location.pathname.split('/')[1]

    if ((SUPPORTED as readonly string[]).includes(seg)) {
      location.replace('/' + seg + '/404' + location.search + location.hash)
      return
    }

    const locale = getExplicitLanguage() ?? detectBrowserLocale()
    location.replace('/' + locale + location.pathname + location.search + location.hash)
  }, [])

  return null
}
