// Generates weapon stat mapping: weapon skillName (base, without suffix)
// → gemTermId. Built from upstream weapon JSONs at sync time.
//
// Primary/elemental stats: resolved via blackboard[0].key → gemTermId
// Special abilities: resolved via CN name → GemTable → gemTermId
// ================================================================================

import { existsSync, readFileSync, readdirSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { buildGemTableLookup } from './stat-mapping'

// ── Blackboard key → gemTermId suffix mapping ────────────────────────────

/** Maps weapon blackboard keys to gemTermId suffixes (the part after "gat_passive_attr_"). */
const BLACKBOARD_TO_GEM_SUFFIX: Record<string, string> = {
  str: 'str',
  agi: 'agi',
  wisd: 'wisd',
  will: 'will',
  mainattr: 'main',
  atk: 'atk',
  hp: 'hp',
  phydam: 'phydam',
  firedam: 'firedam',
  pulsedam: 'pulsedam',
  electrondam: 'pulsedam',    // engine uses "electrondam", config uses "pulsedam"
  icedam: 'icedam',
  crystdam: 'icedam',         // engine uses "crystdam", config uses "icedam"
  naturaldam: 'naturaldam',
  crirate: 'crirate',
  usp: 'usp',
  usgs: 'usp',                // engine uses "usgs", config uses "usp"
  heal: 'heal',
  physpell: 'physpell',
  spelldam: 'magicdam',       // engine uses "spelldam", config uses "magicdam"
}

// ── Types ─────────────────────────────────────────────────────────────────

export interface WeaponStatMappingResult {
  written: string
  count: number
}

// ── Generator ─────────────────────────────────────────────────────────────

export function generateWeaponStatMapping(
  imagedbPath: string,
  akedataPath: string,
  translationPath: string,
  outputDir: string,
): WeaponStatMappingResult {
  const weaponDir = join(imagedbPath, 'public', 'CH', 'weapon')
  const fallbackDir = join(akedataPath, 'output', 'CN', 'weapon')
  const dir = existsSync(weaponDir) ? weaponDir : existsSync(fallbackDir) ? fallbackDir : null
  if (!dir) return { written: '', count: 0 }

  // Build GemTable lookup for special abilities
  const gemLookup = buildGemTableLookup(akedataPath, translationPath)
  const cnToGem = new Map(Object.entries(gemLookup.cnToGem))

  const mapping: Record<string, string> = {}

  for (const file of readdirSync(dir)) {
    if (!file.endsWith('.json') || file === 'manifest.json') continue
    const data = JSON.parse(readFileSync(join(dir, file), 'utf-8'))

    for (const skill of (data.skilllist ?? []) as Array<{ skillName: string; blackboard?: { key: string }[] }>) {
      // Strip suffix (·大, ·中, ·小, [L], etc.)
      const idx = skill.skillName.indexOf('·')
      const baseName = idx === -1 ? skill.skillName : skill.skillName.slice(0, idx)

      if (mapping[baseName]) continue

      const bbKey = skill.blackboard?.[0]?.key
      if (!bbKey) {
        // Special ability: match by CN name in GemTable
        const gemId = cnToGem.get(baseName)
        if (gemId) mapping[baseName] = gemId
        continue
      }

      // Primary/elemental: map blackboard key → gemTermId
      const suffix = BLACKBOARD_TO_GEM_SUFFIX[bbKey]
      if (suffix) {
        mapping[baseName] = `gat_passive_attr_${suffix}`
      }
    }
  }

  // Write generated file
  mkdirSync(outputDir, { recursive: true })
  const outPath = join(outputDir, 'weapon-stat-mapping.ts')
  const lines = [
    '// Auto-generated by sync-game-data. Do not edit manually.',
    '// Maps weapon skillName (base form, without suffix) → gemTermId.',
    '// Source: AKEDatabase/public/CH/weapon/ + GemTable',
    '',
    'export const WEAPON_STAT_TO_GEM_TERM: Record<string, string> = {',
    ...Object.entries(mapping)
      .sort(([a], [b]) => a.localeCompare(b, 'zh-CN'))
      .map(([cn, gem]) => `  '${cn}': '${gem}',`),
    '}',
    '',
  ]
  writeFileSync(outPath, lines.join('\n'), 'utf-8')

  return { written: outPath, count: Object.keys(mapping).length }
}
