// Generates equip CN stat name → canonical key mapping.
// Written to src/generated/equip-stat-mapping.ts during sync.
// Keys are attrType (number) or compositeAttr (string) — no gemTermId normalization.
// ================================================================================

import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { parseJsonSafe } from './json-utils'
import { loadTextTable } from './stat-mapping'

export interface EquipStatMappingResult {
  written: string
  count: number
}

export function generateEquipStatMapping(
  akedataPath: string,
  outputDir: string,
): EquipStatMappingResult {
  const tt = loadTextTable(akedataPath, 'zh-CN')

  const lines = [
    '// Auto-generated by sync-game-data. Do not edit manually.',
    '// Maps equip CN stat name → canonical key (attrType / compositeAttr).',
    '// Source: AttributeShowConfigTable + CompositeAttributeShowConfigTable',
    '',
    'const _CN_TO_KEY: Record<string, string> = {',
  ]

  let count = 0
  const seen = new Set<string>()

  // AttributeShowConfigTable: CN name → attrType
  const attrCfgPath = join(akedataPath, 'TableCfg', 'AttributeShowConfigTable.json')
  if (existsSync(attrCfgPath)) {
    const cfg = parseJsonSafe(attrCfgPath) as Record<string, { list: { name: { id: string } }[] }>
    for (const [attrType, data] of Object.entries(cfg)) {
      if (!data.list?.[0]?.name?.id) continue
      const cn = tt[data.list[0].name.id]
      if (cn) {
        const line = `  ${JSON.stringify(cn)}: ${JSON.stringify(attrType)},`
        if (!seen.has(line)) {
          seen.add(line)
          lines.push(line)
          count++
        }
      }
    }
  }

  // CompositeAttributeShowConfigTable: CN name → compositeAttr
  const compCfgPath = join(akedataPath, 'TableCfg', 'CompositeAttributeShowConfigTable.json')
  if (existsSync(compCfgPath)) {
    const cfg = parseJsonSafe(compCfgPath) as Record<string, { list: { name: { id: string } }[] }>
    for (const [compositeAttr, data] of Object.entries(cfg)) {
      if (!data.list?.[0]?.name?.id) continue
      const cn = tt[data.list[0].name.id]
      if (cn) {
        const line = `  ${JSON.stringify(cn)}: ${JSON.stringify(compositeAttr)},`
        if (!seen.has(line)) {
          seen.add(line)
          lines.push(line)
          count++
        }
      }
    }
  }

  lines.push('};', '')
  lines.push(
    '/** Resolve a CN equip stat name to its canonical key. */',
    'export function resolveEquipStatKey(cnName: string): string {',
    '  return _CN_TO_KEY[cnName] ?? cnName;',
    '}',
    '',
  )

  mkdirSync(outputDir, { recursive: true })
  const outPath = join(outputDir, 'equip-stat-mapping.ts')
  writeFileSync(outPath, lines.join('\n'), 'utf-8')

  return { written: outPath, count }
}
