import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  buildCharacterWikiData,
  type CharacterWikiData,
  type CharacterWikiSource,
} from './build-character-wiki'
import { parseJsonSafe } from './json-utils'
import { loadAllTextTables, SUPPORTED_LOCALES } from './stat-mapping'

export interface CharacterResult {
  written: string[]
  dataWritten: string | null
  detailFiles: string[]
  enumFile: string | null
  count: number
  missing: number
  wikiData: CharacterWikiData
}

function loadTable(akedataPath: string, table: string): unknown {
  return parseJsonSafe(join(akedataPath, 'TableCfg', `${table}.json`))
}

function loadAttributeVariableNames(imagedbPath: string): Record<string, string> {
  const maps = JSON.parse(readFileSync(join(imagedbPath, 'public', 'CH', 'maps.json'), 'utf8')) as {
    ATTR_MAP_EN?: Record<string, string>
  }
  return maps.ATTR_MAP_EN ?? {}
}

function writeCharacterSummaries(dataOutputDir: string, summaries: ReturnType<typeof buildCharacterWikiData>['summaries']): string {
  const wikiDir = join(dataOutputDir, 'wiki')
  mkdirSync(wikiDir, { recursive: true })
  const path = join(wikiDir, 'characters.ts')
  writeFileSync(
    path,
    [
      '// Auto-generated by generate-characters.ts during sync-game-data.',
      '// DO NOT EDIT MANUALLY.',
      "import type { WikiCharacterSummary } from '@/types/wiki'",
      '',
      `export const wikiCharacters = ${JSON.stringify(summaries, null, 2)} satisfies WikiCharacterSummary[]`,
      '',
    ].join('\n'),
    'utf8'
  )
  return path
}

export function generateCharacterI18n(
  akedataPath: string,
  imagedbPath: string,
  outputDir: string,
  dataOutputDir?: string
): CharacterResult {
  const source: CharacterWikiSource = {
    attributeVariableNames: loadAttributeVariableNames(imagedbPath),
    characterConst: loadTable(akedataPath, 'CharacterConst') as CharacterWikiSource['characterConst'],
    characterTable: loadTable(akedataPath, 'CharacterTable') as CharacterWikiSource['characterTable'],
    characterGrowthTable: loadTable(akedataPath, 'CharGrowthTable') as CharacterWikiSource['characterGrowthTable'],
    characterPotentialTable: loadTable(akedataPath, 'CharacterPotentialTable') as CharacterWikiSource['characterPotentialTable'],
    potentialTalentEffectTable: loadTable(akedataPath, 'PotentialTalentEffectTable') as CharacterWikiSource['potentialTalentEffectTable'],
    skillPatchTable: loadTable(akedataPath, 'SkillPatchTable') as CharacterWikiSource['skillPatchTable'],
    spaceshipCharacterSkillTable: loadTable(akedataPath, 'SpaceshipCharSkillTable') as CharacterWikiSource['spaceshipCharacterSkillTable'],
    spaceshipSkillTable: loadTable(akedataPath, 'SpaceshipSkillTable') as CharacterWikiSource['spaceshipSkillTable'],
    characterTypeTable: loadTable(akedataPath, 'CharTypeTable') as CharacterWikiSource['characterTypeTable'],
    characterProfessionTable: loadTable(akedataPath, 'CharProfessionTable') as CharacterWikiSource['characterProfessionTable'],
    itemTable: loadTable(akedataPath, 'ItemTable') as CharacterWikiSource['itemTable'],
    textTables: loadAllTextTables(akedataPath),
  }
  const generated = buildCharacterWikiData(source)
  const written: string[] = []
  const i18nDir = join(outputDir, 'characters')
  mkdirSync(i18nDir, { recursive: true })

  for (const locale of SUPPORTED_LOCALES) {
    const path = join(i18nDir, `${locale}.json`)
    const names = Object.fromEntries(
      generated.summaries.map((character) => [character.id, character.name[locale]])
    )
    writeFileSync(path, `${JSON.stringify(names, null, 2)}\n`, 'utf8')
    written.push(path)
  }

  if (!dataOutputDir) {
    return {
      written,
      dataWritten: null,
      detailFiles: [],
      enumFile: null,
      count: generated.summaries.length,
      missing: 0,
      wikiData: generated,
    }
  }

  const dataWritten = writeCharacterSummaries(dataOutputDir, generated.summaries)
  const detailDir = join(dataOutputDir, 'wiki', 'characters')
  rmSync(detailDir, { recursive: true, force: true })
  mkdirSync(detailDir, { recursive: true })
  const detailFiles = Object.entries(generated.details).map(([id, detail]) => {
    const path = join(detailDir, `${id}.json`)
    writeFileSync(path, `${JSON.stringify(detail, null, 2)}\n`, 'utf8')
    return path
  })
  const enumFile = join(dataOutputDir, 'wiki', 'character-enums.json')
  writeFileSync(enumFile, `${JSON.stringify(generated.enumLabels, null, 2)}\n`, 'utf8')

  return {
    written,
    dataWritten,
    detailFiles,
    enumFile,
    count: generated.summaries.length,
    missing: 0,
    wikiData: generated,
  }
}
