import { execSync } from "node:child_process"
import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { resolve, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, "..")
const generatedDir = resolve(root, "src", "generated")

function git(cmd) {
  try {
    return execSync(`git ${cmd}`, { cwd: root, encoding: "utf-8" }).trim()
  } catch {
    return ""
  }
}

const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf-8"))

// 全部 commit: 短hash + ISO时间 + 完整提交信息（用于 changelog.json，按需加载）
const DELIMITER = '---CHANGELOG_ENTRY_END---'
const changelogRaw = git(`log --format="%h %cI%n%B%n${DELIMITER}"`)
const changelog = changelogRaw
  ? changelogRaw
      .split(DELIMITER)
      .map(s => s.trim())
      .filter(Boolean)
      .map(entry => entry.replace(/(Co-authored-by:\s*.*?)\s*<[^>]+>/g, '$1').trim())
  : []

// 统计含 [force] 标记的 tag 数量，生成强制升级序列号
// Priority 1: CI 注入的 FORCE_UPGRADE_SERIAL 环境变量（通过 GitHub API 计算）
// Priority 2: 从 force-N 轻量级 tag 名提取序列号（始终最多一个）
function getForceUpgradeSerial() {
  const tag = (git("tag -l force-*") || "").trim()
  if (!tag) return 0
  const m = tag.match(/^force-(\d+)$/)
  return m ? Number(m[1]) : 0
}

// 优先从 CI 注入的 DEPLOY_TAG 环境变量读取 semver（构建机可能拉不到完整的 git tags）
// 其次读取当前 HEAD 指向的 tag 中的 semver，本地开发无 tag 时 fallback 到 package.json
function getSemver() {
  // Priority 1: CI-provided tag name (e.g., v1.2.0)
  const ciTag = process.env.DEPLOY_TAG
  if (ciTag) {
    const m = String(ciTag).trim().match(/^v(\d+\.\d+\.\d+)/)
    if (m) return m[1]
  }
  // Priority 2: git tag pointing at HEAD
  const tags = git("tag -l v* --points-at HEAD") || ""
  const lines = tags.split("\n").filter(Boolean)
  for (const tag of lines) {
    const m = tag.trim().match(/^v(\d+\.\d+\.\d+)/)
    if (m) return m[1]
  }
  // Priority 3: package.json version
  return pkg.version || "0.0.0"
}

const semver = getSemver()
const commitHash = git("rev-parse --short HEAD") || "unknown"
const count = Number(git("rev-list --count HEAD")) || 0
const derivedVersion = `${semver}-${commitHash}`

// 轮询用轻量文件，不含 changelog
const version = {
  commit: commitHash,
  count,
  commitTime: git("log -1 --format=%cI") || "",
  buildTime: new Date().toISOString(),
  version: derivedVersion,
  forceUpgradeSerial: getForceUpgradeSerial(),
}

const outPath = resolve(root, "public", "version.json")
writeFileSync(outPath, JSON.stringify(version, null, 2))

// 详细更新日志，按需加载
const changelogPath = resolve(root, "public", "changelog.json")
writeFileSync(changelogPath, JSON.stringify({ changelog }, null, 2))

mkdirSync(generatedDir, { recursive: true })
const tsPath = resolve(generatedDir, "version-data.ts")
writeFileSync(tsPath, `// Auto-generated by scripts/generate-version.mjs
import type { VersionInfo } from '@/types/version'

export const versionData: VersionInfo = ${JSON.stringify(version, null, 2)}
`)

console.log(`version.json written: ${JSON.stringify(version)}`)
