import { execSync } from "node:child_process"
import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { resolve, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, "..")
const generatedDir = resolve(root, "src", "generated")

function git(cmd) {
  try {
    return execSync(`git ${cmd}`, { cwd: root, encoding: "utf-8" }).trim()
  } catch {
    return ""
  }
}

const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf-8"))

// 提取最近 10 条 commit message 作为更新日志
const changelogRaw = git("log -10 --format=%s")
const changelog = changelogRaw
  ? changelogRaw.split("\n").filter(Boolean)
  : []

// 版本号 = package.json 的 major.minor + git commit count 作为 patch
const count = Number(git("rev-list --count HEAD")) || 0
const baseVersion = (pkg.version || "0.0.0").split('.').slice(0, 2).join('.')
const derivedVersion = `${baseVersion}.${count}`

const version = {
  commit: git("rev-parse --short HEAD") || "unknown",
  count,
  message: git("log -1 --format=%s") || "",
  commitTime: git("log -1 --format=%cI") || "",
  buildTime: new Date().toISOString(),
  version: derivedVersion,
  changelog,
}

const outPath = resolve(root, "public", "version.json")
writeFileSync(outPath, JSON.stringify(version, null, 2))

mkdirSync(generatedDir, { recursive: true })
const tsPath = resolve(generatedDir, "version-data.ts")
writeFileSync(tsPath, `// Auto-generated by scripts/generate-version.mjs
import type { VersionInfo } from '@/types/version'

export const versionData: VersionInfo = ${JSON.stringify(version, null, 2)}
`)

console.log(`version.json written: ${JSON.stringify(version)}`)
