// Auto-generated by scripts/generate-characters-index.mjs
// Do not edit manually.

import type { CharacterGuideData } from '@/types/character-guide'

import gilbertaData from './gilberta.json'
import laevatainData from './laevatain.json'
import lifengData from './lifeng.json'
import pogranichnikData from './pogranichnik.json'
import rossiData from './rossi.json'
import tangtangData from './tangtang.json'
import zhuangfangyiData from './zhuangfangyi.json'

/** All character guide data, keyed by lowercase ID */
export const characterGuideData: Record<string, CharacterGuideData> = {
  'gilberta': gilbertaData as CharacterGuideData,
  'laevatain': laevatainData as CharacterGuideData,
  'lifeng': lifengData as CharacterGuideData,
  'pogranichnik': pogranichnikData as CharacterGuideData,
  'rossi': rossiData as CharacterGuideData,
  'tangtang': tangtangData as CharacterGuideData,
  'zhuangfangyi': zhuangfangyiData as CharacterGuideData,
}

/** Ordered list of character guide data */
export const characterGuideList: CharacterGuideData[] = [
  gilbertaData as CharacterGuideData,
  laevatainData as CharacterGuideData,
  lifengData as CharacterGuideData,
  pogranichnikData as CharacterGuideData,
  rossiData as CharacterGuideData,
  tangtangData as CharacterGuideData,
  zhuangfangyiData as CharacterGuideData,
]

export type { CharacterGuideData }
